services:
  app:
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 1341:1341
      - 3041:3041
    depends_on:
      postgres:
        condition: service_healthy
      garage:
        condition: service_healthy
    env_file:
      - .env

  garage-webui:
    image: khairul169/garage-webui:1.1.0
    container_name: bureaucat-garage-webui
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
    ports:
      - 3909:3909
    depends_on:
      garage:
        condition: service_healthy
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

  garage:
    image: dxflrs/garage:v2.2.0
    restart: unless-stopped
    container_name: bureaucat-garage
    ports:
      - 3900:3900 # S3 API
      - 3903:3903 # admin API
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - ./garage/meta:/var/lib/garage/meta
      - ./garage/data:/var/lib/garage/data
    healthcheck:
      test: ["CMD", "/garage", "status"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  pgweb:
    image: sosedoff/pgweb:0.17.0
    env_file:
      - .pgweb.env
    ports:
      - 8081:8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"]
      interval: 5s

  postgres:
    image: postgres:18.1-alpine3.23
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/18/docker
    env_file:
      - .postgres.env
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 10s
      timeout: 5s
      retries: 5
