// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pat.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPersonalAccessToken = `-- name: CreatePersonalAccessToken :one
INSERT INTO personal_access_tokens (user_id, name, token_hash, expires_at, scope)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, expires_at, last_used_at, created_at, scope
`

type CreatePersonalAccessTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Scope     string             `json:"scope"`
}

func (q *Queries) CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPersonalAccessToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.Scope,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}

const deletePersonalAccessToken = `-- name: DeletePersonalAccessToken :exec
DELETE FROM personal_access_tokens
WHERE id = $1 AND user_id = $2
`

type DeletePersonalAccessTokenParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeletePersonalAccessToken(ctx context.Context, arg DeletePersonalAccessTokenParams) error {
	_, err := q.db.Exec(ctx, deletePersonalAccessToken, arg.ID, arg.UserID)
	return err
}

const getPersonalAccessTokenByHash = `-- name: GetPersonalAccessTokenByHash :one
SELECT pat.id, pat.user_id, pat.expires_at, pat.last_used_at, pat.created_at, pat.scope,
       u.username, u.user_type
FROM personal_access_tokens pat
JOIN users u ON pat.user_id = u.id
WHERE pat.token_hash = $1
  AND (pat.expires_at IS NULL OR pat.expires_at > NOW())
`

type GetPersonalAccessTokenByHashRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Scope      string             `json:"scope"`
	Username   string             `json:"username"`
	UserType   string             `json:"user_type"`
}

func (q *Queries) GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (GetPersonalAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getPersonalAccessTokenByHash, tokenHash)
	var i GetPersonalAccessTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Scope,
		&i.Username,
		&i.UserType,
	)
	return i, err
}

const listPersonalAccessTokensByUser = `-- name: ListPersonalAccessTokensByUser :many
SELECT id, name, expires_at, last_used_at, created_at, scope
FROM personal_access_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListPersonalAccessTokensByUserRow struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Scope      string             `json:"scope"`
}

func (q *Queries) ListPersonalAccessTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListPersonalAccessTokensByUserRow, error) {
	rows, err := q.db.Query(ctx, listPersonalAccessTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPersonalAccessTokensByUserRow{}
	for rows.Next() {
		var i ListPersonalAccessTokensByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePersonalAccessTokenLastUsed = `-- name: UpdatePersonalAccessTokenLastUsed :exec
UPDATE personal_access_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdatePersonalAccessTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updatePersonalAccessTokenLastUsed, id)
	return err
}

const updatePersonalAccessTokenScope = `-- name: UpdatePersonalAccessTokenScope :one
UPDATE personal_access_tokens
SET scope = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, expires_at, last_used_at, created_at, scope
`

type UpdatePersonalAccessTokenScopeParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Scope  string    `json:"scope"`
}

type UpdatePersonalAccessTokenScopeRow struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Name       string             `json:"name"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Scope      string             `json:"scope"`
}

func (q *Queries) UpdatePersonalAccessTokenScope(ctx context.Context, arg UpdatePersonalAccessTokenScopeParams) (UpdatePersonalAccessTokenScopeRow, error) {
	row := q.db.QueryRow(ctx, updatePersonalAccessTokenScope, arg.ID, arg.UserID, arg.Scope)
	var i UpdatePersonalAccessTokenScopeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.Scope,
	)
	return i, err
}
