// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :one

INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING id, project_id, user_id, role, joined_at
`

type AddProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

// ==================== PROJECT MEMBERS ====================
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	var i ProjectMember
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const addTaskAssignee = `-- name: AddTaskAssignee :one

INSERT INTO task_assignees (task_id, user_id, assigned_by)
VALUES ($1, $2, $3)
RETURNING id, task_id, user_id, assigned_at, assigned_by
`

type AddTaskAssigneeParams struct {
	TaskID     uuid.UUID `json:"task_id"`
	UserID     uuid.UUID `json:"user_id"`
	AssignedBy uuid.UUID `json:"assigned_by"`
}

// ==================== TASK ASSIGNEES ====================
func (q *Queries) AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error) {
	row := q.db.QueryRow(ctx, addTaskAssignee, arg.TaskID, arg.UserID, arg.AssignedBy)
	var i TaskAssignee
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.AssignedAt,
		&i.AssignedBy,
	)
	return i, err
}

const addTaskLabel = `-- name: AddTaskLabel :exec

INSERT INTO task_labels (task_id, label_id, added_by)
VALUES ($1, $2, $3)
`

type AddTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
	AddedBy uuid.UUID `json:"added_by"`
}

// ==================== TASK LABELS ====================
func (q *Queries) AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error {
	_, err := q.db.Exec(ctx, addTaskLabel, arg.TaskID, arg.LabelID, arg.AddedBy)
	return err
}

const countAllProjects = `-- name: CountAllProjects :one
SELECT COUNT(*)
FROM projects p
WHERE p.deleted_at IS NULL
`

func (q *Queries) CountAllProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllProjectsFiltered = `-- name: CountAllProjectsFiltered :one
SELECT COUNT(*)
FROM projects p
WHERE p.deleted_at IS NULL
  AND ($1::text IS NULL OR p.name ILIKE '%' || $1 || '%' OR p.project_key ILIKE '%' || $1 || '%' OR p.description ILIKE '%' || $1 || '%')
`

func (q *Queries) CountAllProjectsFiltered(ctx context.Context, search pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countAllProjectsFiltered, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectMembers = `-- name: CountProjectMembers :one
SELECT COUNT(*) FROM project_members WHERE project_id = $1
`

func (q *Queries) CountProjectMembers(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectMembers, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectTasks = `-- name: CountProjectTasks :one
SELECT COUNT(*)
FROM tasks
WHERE project_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTasks, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProjectTasksFiltered = `-- name: CountProjectTasksFiltered :one
SELECT COUNT(*)
FROM tasks t
JOIN project_states ps ON t.state_id = ps.id
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
  AND ($2::uuid IS NULL OR t.state_id = $2)
  AND ($3::state_type IS NULL OR ps.state_type = $3)
  AND ($4::int IS NULL OR t.priority = $4)
  AND ($5::uuid IS NULL OR t.created_by = $5)
  AND ($6::uuid IS NULL OR EXISTS (SELECT 1 FROM task_assignees ta WHERE ta.task_id = t.id AND ta.user_id = $6))
  AND ($7::text IS NULL OR t.title ILIKE '%' || $7 || '%' OR t.description ILIKE '%' || $7 || '%')
  AND ($8::timestamptz IS NULL OR t.created_at >= $8)
  AND ($9::timestamptz IS NULL OR t.created_at <= $9)
`

type CountProjectTasksFilteredParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	StateID    pgtype.UUID        `json:"state_id"`
	StateType  NullStateType      `json:"state_type"`
	Priority   pgtype.Int4        `json:"priority"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
	Search     pgtype.Text        `json:"search"`
	FromDate   pgtype.Timestamptz `json:"from_date"`
	ToDate     pgtype.Timestamptz `json:"to_date"`
}

func (q *Queries) CountProjectTasksFiltered(ctx context.Context, arg CountProjectTasksFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectTasksFiltered,
		arg.ProjectID,
		arg.StateID,
		arg.StateType,
		arg.Priority,
		arg.CreatedBy,
		arg.AssignedTo,
		arg.Search,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTaskComments = `-- name: CountTaskComments :one
SELECT COUNT(*) FROM comments WHERE task_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTaskComments(ctx context.Context, taskID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTaskComments, taskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksByAssignee = `-- name: CountTasksByAssignee :one
SELECT COUNT(*)
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN task_assignees ta ON t.id = ta.task_id
WHERE ta.user_id = $1 AND t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND ps.state_type NOT IN ('completed', 'cancelled')
`

func (q *Queries) CountTasksByAssignee(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksByAssignee, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTasksInState = `-- name: CountTasksInState :one
SELECT COUNT(*) FROM tasks WHERE state_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTasksInState(ctx context.Context, stateID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTasksInState, stateID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserProjects = `-- name: CountUserProjects :one
SELECT COUNT(*)
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
`

func (q *Queries) CountUserProjects(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProjects, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserProjectsFiltered = `-- name: CountUserProjectsFiltered :one
SELECT COUNT(*)
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
  AND ($2::text IS NULL OR p.name ILIKE '%' || $2 || '%' OR p.project_key ILIKE '%' || $2 || '%' OR p.description ILIKE '%' || $2 || '%')
`

type CountUserProjectsFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Search pgtype.Text `json:"search"`
}

func (q *Queries) CountUserProjectsFiltered(ctx context.Context, arg CountUserProjectsFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserProjectsFiltered, arg.UserID, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one

INSERT INTO activity_log (task_id, activity_type, actor_id, field_name, old_value, new_value, checksum, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, activity_type, actor_id, field_name, old_value, new_value, created_at, checksum
`

type CreateActivityLogParams struct {
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	Checksum     string             `json:"checksum"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// ==================== ACTIVITY LOG ====================
func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.TaskID,
		arg.ActivityType,
		arg.ActorID,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Checksum,
		arg.CreatedAt,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ActivityType,
		&i.ActorID,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
		&i.Checksum,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one

INSERT INTO comments (task_id, content, created_by)
VALUES ($1, $2, $3)
RETURNING id, task_id, content, version, created_by, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	TaskID    uuid.UUID `json:"task_id"`
	Content   string    `json:"content"`
	CreatedBy uuid.UUID `json:"created_by"`
}

// ==================== COMMENTS ====================
func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment, arg.TaskID, arg.Content, arg.CreatedBy)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one

INSERT INTO projects (project_key, name, description, icon_id, cover_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	ProjectKey  string      `json:"project_key"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
	CoverID     pgtype.UUID `json:"cover_id"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

// ==================== PROJECTS ====================
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectKey,
		arg.Name,
		arg.Description,
		arg.IconID,
		arg.CoverID,
		arg.CreatedBy,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProjectLabel = `-- name: CreateProjectLabel :one

INSERT INTO project_labels (project_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, project_id, name, color, created_at
`

type CreateProjectLabelParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
}

// ==================== PROJECT LABELS ====================
func (q *Queries) CreateProjectLabel(ctx context.Context, arg CreateProjectLabelParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, createProjectLabel, arg.ProjectID, arg.Name, arg.Color)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const createProjectState = `-- name: CreateProjectState :one

INSERT INTO project_states (project_id, state_type, name, color, position, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, state_type, name, color, position, is_default, created_at
`

type CreateProjectStateParams struct {
	ProjectID uuid.UUID   `json:"project_id"`
	StateType string      `json:"state_type"`
	Name      string      `json:"name"`
	Color     pgtype.Text `json:"color"`
	Position  int32       `json:"position"`
	IsDefault bool        `json:"is_default"`
}

// ==================== PROJECT STATES ====================
func (q *Queries) CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, createProjectState,
		arg.ProjectID,
		arg.StateType,
		arg.Name,
		arg.Color,
		arg.Position,
		arg.IsDefault,
	)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (project_id, task_number, title, description, state_id, priority, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, task_number, title, description, state_id, priority, created_by, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProjectID   uuid.UUID   `json:"project_id"`
	TaskNumber  int32       `json:"task_number"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	StateID     uuid.UUID   `json:"state_id"`
	Priority    int32       `json:"priority"`
	CreatedBy   uuid.UUID   `json:"created_by"`
}

// ==================== TASKS ====================
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.TaskNumber,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.Priority,
		arg.CreatedBy,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createTaskTemplate = `-- name: CreateTaskTemplate :one

INSERT INTO task_templates (project_id, name, title, description, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, name, title, description, created_by, created_at, updated_at
`

type CreateTaskTemplateParams struct {
	ProjectID   uuid.UUID `json:"project_id"`
	Name        string    `json:"name"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedBy   uuid.UUID `json:"created_by"`
}

// ==================== TASK TEMPLATES ====================
func (q *Queries) CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, createTaskTemplate,
		arg.ProjectID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectLabel = `-- name: DeleteProjectLabel :exec
DELETE FROM project_labels WHERE id = $1
`

func (q *Queries) DeleteProjectLabel(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectLabel, id)
	return err
}

const deleteProjectState = `-- name: DeleteProjectState :exec
DELETE FROM project_states WHERE id = $1
`

func (q *Queries) DeleteProjectState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProjectState, id)
	return err
}

const deleteTaskTemplate = `-- name: DeleteTaskTemplate :exec
DELETE FROM task_templates WHERE id = $1
`

func (q *Queries) DeleteTaskTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTemplate, id)
	return err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.task_id, c.content, c.version, c.created_by, c.created_at, c.updated_at, c.deleted_at,
       u.username, u.first_name, u.last_name
FROM comments c
JOIN users u ON c.created_by = u.id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCommentByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  string             `json:"username"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Username,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getDefaultProjectState = `-- name: GetDefaultProjectState :one
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultProjectState(ctx context.Context, projectID uuid.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getDefaultProjectState, projectID)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getLastActivityChecksum = `-- name: GetLastActivityChecksum :one
SELECT checksum
FROM activity_log
WHERE task_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLastActivityChecksum(ctx context.Context, taskID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastActivityChecksum, taskID)
	var checksum string
	err := row.Scan(&checksum)
	return checksum, err
}

const getNextTaskNumber = `-- name: GetNextTaskNumber :one
SELECT COALESCE(MAX(task_number), 0) + 1 AS next_number
FROM tasks
WHERE project_id = $1
`

func (q *Queries) GetNextTaskNumber(ctx context.Context, projectID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextTaskNumber, projectID)
	var next_number int32
	err := row.Scan(&next_number)
	return next_number, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at
FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at
FROM projects
WHERE project_key = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByKey(ctx context.Context, projectKey string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, projectKey)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectLabelByID = `-- name: GetProjectLabelByID :one
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE id = $1
`

func (q *Queries) GetProjectLabelByID(ctx context.Context, id uuid.UUID) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, getProjectLabelByID, id)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectLabelByProjectAndName = `-- name: GetProjectLabelByProjectAndName :one
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetProjectLabelByProjectAndNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetProjectLabelByProjectAndName(ctx context.Context, arg GetProjectLabelByProjectAndNameParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, getProjectLabelByProjectAndName, arg.ProjectID, arg.Name)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectMember = `-- name: GetProjectMember :one
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.joined_at,
       u.username, u.email, u.first_name, u.last_name
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1 AND pm.user_id = $2
`

type GetProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

type GetProjectMemberRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
}

func (q *Queries) GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, getProjectMember, arg.ProjectID, arg.UserID)
	var i GetProjectMemberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Username,
		&i.Email,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getProjectStateByID = `-- name: GetProjectStateByID :one
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE id = $1
`

func (q *Queries) GetProjectStateByID(ctx context.Context, id uuid.UUID) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByID, id)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectStateByProjectAndName = `-- name: GetProjectStateByProjectAndName :one

SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1 AND name = $2
LIMIT 1
`

type GetProjectStateByProjectAndNameParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Name      string    `json:"name"`
}

// ==================== IMPORT HELPERS ====================
func (q *Queries) GetProjectStateByProjectAndName(ctx context.Context, arg GetProjectStateByProjectAndNameParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, getProjectStateByProjectAndName, arg.ProjectID, arg.Name)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.id = $1 AND t.deleted_at IS NULL
`

type GetTaskByIDRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	TaskNumber       int32              `json:"task_number"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StateID          uuid.UUID          `json:"state_id"`
	Priority         int32              `json:"priority"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey       string             `json:"project_key"`
	StateName        string             `json:"state_name"`
	StateType        string             `json:"state_type"`
	StateColor       pgtype.Text        `json:"state_color"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
}

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i GetTaskByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.StateName,
		&i.StateType,
		&i.StateColor,
		&i.CreatorUsername,
		&i.CreatorFirstName,
		&i.CreatorLastName,
	)
	return i, err
}

const getTaskByProjectAndNumber = `-- name: GetTaskByProjectAndNumber :one
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.project_id = $1 AND t.task_number = $2 AND t.deleted_at IS NULL
`

type GetTaskByProjectAndNumberParams struct {
	ProjectID  uuid.UUID `json:"project_id"`
	TaskNumber int32     `json:"task_number"`
}

type GetTaskByProjectAndNumberRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	TaskNumber       int32              `json:"task_number"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StateID          uuid.UUID          `json:"state_id"`
	Priority         int32              `json:"priority"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey       string             `json:"project_key"`
	StateName        string             `json:"state_name"`
	StateType        string             `json:"state_type"`
	StateColor       pgtype.Text        `json:"state_color"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
}

func (q *Queries) GetTaskByProjectAndNumber(ctx context.Context, arg GetTaskByProjectAndNumberParams) (GetTaskByProjectAndNumberRow, error) {
	row := q.db.QueryRow(ctx, getTaskByProjectAndNumber, arg.ProjectID, arg.TaskNumber)
	var i GetTaskByProjectAndNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectKey,
		&i.StateName,
		&i.StateType,
		&i.StateColor,
		&i.CreatorUsername,
		&i.CreatorFirstName,
		&i.CreatorLastName,
	)
	return i, err
}

const getTaskTemplateByID = `-- name: GetTaskTemplateByID :one
SELECT id, project_id, name, title, description, created_by, created_at, updated_at FROM task_templates WHERE id = $1
`

func (q *Queries) GetTaskTemplateByID(ctx context.Context, id uuid.UUID) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, getTaskTemplateByID, id)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasTaskLabel = `-- name: HasTaskLabel :one
SELECT EXISTS (
    SELECT 1 FROM task_labels
    WHERE task_id = $1 AND label_id = $2
) AS has_label
`

type HasTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasTaskLabel, arg.TaskID, arg.LabelID)
	var has_label bool
	err := row.Scan(&has_label)
	return has_label, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (
    SELECT 1 FROM project_members
    WHERE project_id = $1 AND user_id = $2
) AS is_member
`

type IsProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const isTaskAssignee = `-- name: IsTaskAssignee :one
SELECT EXISTS (
    SELECT 1 FROM task_assignees
    WHERE task_id = $1 AND user_id = $2
) AS is_assignee
`

type IsTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isTaskAssignee, arg.TaskID, arg.UserID)
	var is_assignee bool
	err := row.Scan(&is_assignee)
	return is_assignee, err
}

const listAllProjects = `-- name: ListAllProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, 'admin' AS role
FROM projects p
WHERE p.deleted_at IS NULL
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type ListAllProjectsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllProjectsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]ListAllProjectsRow, error) {
	rows, err := q.db.Query(ctx, listAllProjects, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsRow{}
	for rows.Next() {
		var i ListAllProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllProjectsFiltered = `-- name: ListAllProjectsFiltered :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, 'admin' AS role
FROM projects p
WHERE p.deleted_at IS NULL
  AND ($3::text IS NULL OR p.name ILIKE '%' || $3 || '%' OR p.project_key ILIKE '%' || $3 || '%' OR p.description ILIKE '%' || $3 || '%')
ORDER BY p.name ASC
LIMIT $1 OFFSET $2
`

type ListAllProjectsFilteredParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

type ListAllProjectsFilteredRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListAllProjectsFiltered(ctx context.Context, arg ListAllProjectsFilteredParams) ([]ListAllProjectsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAllProjectsFiltered, arg.Limit, arg.Offset, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllProjectsFilteredRow{}
	for rows.Next() {
		var i ListAllProjectsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLabels = `-- name: ListProjectLabels :many
SELECT id, project_id, name, color, created_at
FROM project_labels
WHERE project_id = $1
ORDER BY name ASC
`

func (q *Queries) ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]ProjectLabel, error) {
	rows, err := q.db.Query(ctx, listProjectLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectLabel{}
	for rows.Next() {
		var i ProjectLabel
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT pm.id, pm.project_id, pm.user_id, pm.role, pm.joined_at,
       u.username, u.email, u.first_name, u.last_name
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
ORDER BY pm.joined_at ASC
`

type ListProjectMembersRow struct {
	ID        uuid.UUID          `json:"id"`
	ProjectID uuid.UUID          `json:"project_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      string             `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectStates = `-- name: ListProjectStates :many
SELECT id, project_id, state_type, name, color, position, is_default, created_at
FROM project_states
WHERE project_id = $1
ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListProjectStates(ctx context.Context, projectID uuid.UUID) ([]ProjectState, error) {
	rows, err := q.db.Query(ctx, listProjectStates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectState{}
	for rows.Next() {
		var i ProjectState
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StateType,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasks = `-- name: ListProjectTasks :many
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.project_id = $1 AND t.deleted_at IS NULL
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectTasksParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListProjectTasksRow struct {
	ID              uuid.UUID          `json:"id"`
	ProjectID       uuid.UUID          `json:"project_id"`
	TaskNumber      int32              `json:"task_number"`
	Title           string             `json:"title"`
	Description     pgtype.Text        `json:"description"`
	StateID         uuid.UUID          `json:"state_id"`
	Priority        int32              `json:"priority"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey      string             `json:"project_key"`
	StateName       string             `json:"state_name"`
	StateType       string             `json:"state_type"`
	StateColor      pgtype.Text        `json:"state_color"`
	CreatorUsername string             `json:"creator_username"`
}

func (q *Queries) ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasks, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTasksRow{}
	for rows.Next() {
		var i ListProjectTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.Priority,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.CreatorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTasksFiltered = `-- name: ListProjectTasksFiltered :many
SELECT t.id, t.project_id, t.task_number, t.title, t.description, t.state_id, t.priority, t.created_by, t.created_at, t.updated_at, t.deleted_at,
       p.project_key,
       ps.name as state_name, ps.state_type, ps.color as state_color,
       u.username as creator_username, u.first_name as creator_first_name, u.last_name as creator_last_name,
       (SELECT COUNT(*) FROM comments c WHERE c.task_id = t.id AND c.deleted_at IS NULL)::bigint as comment_count
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN users u ON t.created_by = u.id
WHERE t.project_id = $1
  AND t.deleted_at IS NULL
  AND ($4::uuid IS NULL OR t.state_id = $4)
  AND ($5::state_type IS NULL OR ps.state_type = $5)
  AND ($6::int IS NULL OR t.priority = $6)
  AND ($7::uuid IS NULL OR t.created_by = $7)
  AND ($8::uuid IS NULL OR EXISTS (SELECT 1 FROM task_assignees ta WHERE ta.task_id = t.id AND ta.user_id = $8))
  AND ($9::text IS NULL OR t.title ILIKE '%' || $9 || '%' OR t.description ILIKE '%' || $9 || '%')
  AND ($10::timestamptz IS NULL OR t.created_at >= $10)
  AND ($11::timestamptz IS NULL OR t.created_at <= $11)
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListProjectTasksFilteredParams struct {
	ProjectID  uuid.UUID          `json:"project_id"`
	Limit      int32              `json:"limit"`
	Offset     int32              `json:"offset"`
	StateID    pgtype.UUID        `json:"state_id"`
	StateType  NullStateType      `json:"state_type"`
	Priority   pgtype.Int4        `json:"priority"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
	Search     pgtype.Text        `json:"search"`
	FromDate   pgtype.Timestamptz `json:"from_date"`
	ToDate     pgtype.Timestamptz `json:"to_date"`
}

type ListProjectTasksFilteredRow struct {
	ID               uuid.UUID          `json:"id"`
	ProjectID        uuid.UUID          `json:"project_id"`
	TaskNumber       int32              `json:"task_number"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	StateID          uuid.UUID          `json:"state_id"`
	Priority         int32              `json:"priority"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	ProjectKey       string             `json:"project_key"`
	StateName        string             `json:"state_name"`
	StateType        string             `json:"state_type"`
	StateColor       pgtype.Text        `json:"state_color"`
	CreatorUsername  string             `json:"creator_username"`
	CreatorFirstName string             `json:"creator_first_name"`
	CreatorLastName  string             `json:"creator_last_name"`
	CommentCount     int64              `json:"comment_count"`
}

func (q *Queries) ListProjectTasksFiltered(ctx context.Context, arg ListProjectTasksFilteredParams) ([]ListProjectTasksFilteredRow, error) {
	rows, err := q.db.Query(ctx, listProjectTasksFiltered,
		arg.ProjectID,
		arg.Limit,
		arg.Offset,
		arg.StateID,
		arg.StateType,
		arg.Priority,
		arg.CreatedBy,
		arg.AssignedTo,
		arg.Search,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectTasksFilteredRow{}
	for rows.Next() {
		var i ListProjectTasksFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.Description,
			&i.StateID,
			&i.Priority,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
			&i.CreatorUsername,
			&i.CreatorFirstName,
			&i.CreatorLastName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT al.id, al.task_id, al.activity_type, al.actor_id, al.field_name, al.old_value, al.new_value, al.created_at, al.checksum,
       u.username, u.first_name, u.last_name
FROM activity_log al
JOIN users u ON al.actor_id = u.id
WHERE al.task_id = $1
ORDER BY al.created_at ASC
`

type ListTaskActivityRow struct {
	ID           uuid.UUID          `json:"id"`
	TaskID       uuid.UUID          `json:"task_id"`
	ActivityType string             `json:"activity_type"`
	ActorID      uuid.UUID          `json:"actor_id"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     []byte             `json:"old_value"`
	NewValue     []byte             `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Checksum     string             `json:"checksum"`
	Username     string             `json:"username"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
}

func (q *Queries) ListTaskActivity(ctx context.Context, taskID uuid.UUID) ([]ListTaskActivityRow, error) {
	rows, err := q.db.Query(ctx, listTaskActivity, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskActivityRow{}
	for rows.Next() {
		var i ListTaskActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.Checksum,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT ta.id, ta.task_id, ta.user_id, ta.assigned_at, ta.assigned_by,
       u.username, u.email, u.first_name, u.last_name
FROM task_assignees ta
JOIN users u ON ta.user_id = u.id
WHERE ta.task_id = $1
ORDER BY ta.assigned_at ASC
`

type ListTaskAssigneesRow struct {
	ID         uuid.UUID          `json:"id"`
	TaskID     uuid.UUID          `json:"task_id"`
	UserID     uuid.UUID          `json:"user_id"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	AssignedBy uuid.UUID          `json:"assigned_by"`
	Username   string             `json:"username"`
	Email      string             `json:"email"`
	FirstName  string             `json:"first_name"`
	LastName   string             `json:"last_name"`
}

func (q *Queries) ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskAssigneesRow{}
	for rows.Next() {
		var i ListTaskAssigneesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.AssignedAt,
			&i.AssignedBy,
			&i.Username,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskComments = `-- name: ListTaskComments :many
SELECT c.id, c.task_id, c.content, c.version, c.created_by, c.created_at, c.updated_at, c.deleted_at,
       u.username, u.first_name, u.last_name
FROM comments c
JOIN users u ON c.created_by = u.id
WHERE c.task_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at ASC
`

type ListTaskCommentsRow struct {
	ID        uuid.UUID          `json:"id"`
	TaskID    uuid.UUID          `json:"task_id"`
	Content   string             `json:"content"`
	Version   int32              `json:"version"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Username  string             `json:"username"`
	FirstName string             `json:"first_name"`
	LastName  string             `json:"last_name"`
}

func (q *Queries) ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error) {
	rows, err := q.db.Query(ctx, listTaskComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskCommentsRow{}
	for rows.Next() {
		var i ListTaskCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Username,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLabels = `-- name: ListTaskLabels :many
SELECT tl.task_id, tl.label_id, tl.added_at, tl.added_by,
       pl.name, pl.color
FROM task_labels tl
JOIN project_labels pl ON tl.label_id = pl.id
WHERE tl.task_id = $1
ORDER BY pl.name ASC
`

type ListTaskLabelsRow struct {
	TaskID  uuid.UUID          `json:"task_id"`
	LabelID uuid.UUID          `json:"label_id"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
	AddedBy uuid.UUID          `json:"added_by"`
	Name    string             `json:"name"`
	Color   pgtype.Text        `json:"color"`
}

func (q *Queries) ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]ListTaskLabelsRow, error) {
	rows, err := q.db.Query(ctx, listTaskLabels, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskLabelsRow{}
	for rows.Next() {
		var i ListTaskLabelsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.LabelID,
			&i.AddedAt,
			&i.AddedBy,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskTemplates = `-- name: ListTaskTemplates :many
SELECT id, project_id, name, title, description, created_by, created_at, updated_at FROM task_templates WHERE project_id = $1 ORDER BY name ASC
`

func (q *Queries) ListTaskTemplates(ctx context.Context, projectID uuid.UUID) ([]TaskTemplate, error) {
	rows, err := q.db.Query(ctx, listTaskTemplates, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskTemplate{}
	for rows.Next() {
		var i TaskTemplate
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByAssignee = `-- name: ListTasksByAssignee :many
SELECT t.id, t.project_id, t.task_number, t.title, t.state_id, t.priority,
       p.project_key, ps.name as state_name, ps.state_type, ps.color as state_color
FROM tasks t
JOIN projects p ON t.project_id = p.id
JOIN project_states ps ON t.state_id = ps.id
JOIN task_assignees ta ON t.id = ta.task_id
WHERE ta.user_id = $1 AND t.deleted_at IS NULL AND p.deleted_at IS NULL
  AND ps.state_type NOT IN ('completed', 'cancelled')
ORDER BY t.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksByAssigneeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListTasksByAssigneeRow struct {
	ID         uuid.UUID   `json:"id"`
	ProjectID  uuid.UUID   `json:"project_id"`
	TaskNumber int32       `json:"task_number"`
	Title      string      `json:"title"`
	StateID    uuid.UUID   `json:"state_id"`
	Priority   int32       `json:"priority"`
	ProjectKey string      `json:"project_key"`
	StateName  string      `json:"state_name"`
	StateType  string      `json:"state_type"`
	StateColor pgtype.Text `json:"state_color"`
}

func (q *Queries) ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error) {
	rows, err := q.db.Query(ctx, listTasksByAssignee, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByAssigneeRow{}
	for rows.Next() {
		var i ListTasksByAssigneeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskNumber,
			&i.Title,
			&i.StateID,
			&i.Priority,
			&i.ProjectKey,
			&i.StateName,
			&i.StateType,
			&i.StateColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjects = `-- name: ListUserProjects :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, pm.role
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
ORDER BY p.name ASC
LIMIT $2 OFFSET $3
`

type ListUserProjectsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListUserProjectsRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error) {
	rows, err := q.db.Query(ctx, listUserProjects, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsRow{}
	for rows.Next() {
		var i ListUserProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserProjectsFiltered = `-- name: ListUserProjectsFiltered :many
SELECT p.id, p.project_key, p.name, p.description, p.icon_id, p.cover_id, p.created_by, p.created_at, p.updated_at, p.deleted_at, pm.role
FROM projects p
JOIN project_members pm ON p.id = pm.project_id
WHERE pm.user_id = $1 AND p.deleted_at IS NULL
  AND ($4::text IS NULL OR p.name ILIKE '%' || $4 || '%' OR p.project_key ILIKE '%' || $4 || '%' OR p.description ILIKE '%' || $4 || '%')
ORDER BY p.name ASC
LIMIT $2 OFFSET $3
`

type ListUserProjectsFilteredParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Search pgtype.Text `json:"search"`
}

type ListUserProjectsFilteredRow struct {
	ID          uuid.UUID          `json:"id"`
	ProjectKey  string             `json:"project_key"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IconID      pgtype.UUID        `json:"icon_id"`
	CoverID     pgtype.UUID        `json:"cover_id"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Role        string             `json:"role"`
}

func (q *Queries) ListUserProjectsFiltered(ctx context.Context, arg ListUserProjectsFilteredParams) ([]ListUserProjectsFilteredRow, error) {
	rows, err := q.db.Query(ctx, listUserProjectsFiltered,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserProjectsFilteredRow{}
	for rows.Next() {
		var i ListUserProjectsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.IconID,
			&i.CoverID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectKeyExists = `-- name: ProjectKeyExists :one
SELECT EXISTS (
    SELECT 1 FROM projects
    WHERE project_key = $1 AND deleted_at IS NULL
) AS exists
`

func (q *Queries) ProjectKeyExists(ctx context.Context, projectKey string) (bool, error) {
	row := q.db.QueryRow(ctx, projectKeyExists, projectKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members
WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const removeTaskAssignee = `-- name: RemoveTaskAssignee :exec
DELETE FROM task_assignees
WHERE task_id = $1 AND user_id = $2
`

type RemoveTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, removeTaskAssignee, arg.TaskID, arg.UserID)
	return err
}

const removeTaskLabel = `-- name: RemoveTaskLabel :exec
DELETE FROM task_labels
WHERE task_id = $1 AND label_id = $2
`

type RemoveTaskLabelParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	LabelID uuid.UUID `json:"label_id"`
}

func (q *Queries) RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error {
	_, err := q.db.Exec(ctx, removeTaskLabel, arg.TaskID, arg.LabelID)
	return err
}

const softDeleteComment = `-- name: SoftDeleteComment :exec
UPDATE comments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteComment, id)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTask, id)
	return err
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2,
    version = version + 1,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, task_id, content, version, created_by, created_at, updated_at, deleted_at
`

type UpdateCommentParams struct {
	ID      uuid.UUID `json:"id"`
	Content string    `json:"content"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = COALESCE($2, name),
    description = COALESCE($3, description),
    icon_id = COALESCE($4, icon_id),
    cover_id = COALESCE($5, cover_id),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_key, name, description, icon_id, cover_id, created_by, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	IconID      pgtype.UUID `json:"icon_id"`
	CoverID     pgtype.UUID `json:"cover_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IconID,
		arg.CoverID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.IconID,
		&i.CoverID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectLabel = `-- name: UpdateProjectLabel :one
UPDATE project_labels
SET name = COALESCE($2, name),
    color = COALESCE($3, color)
WHERE id = $1
RETURNING id, project_id, name, color, created_at
`

type UpdateProjectLabelParams struct {
	ID    uuid.UUID   `json:"id"`
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
}

func (q *Queries) UpdateProjectLabel(ctx context.Context, arg UpdateProjectLabelParams) (ProjectLabel, error) {
	row := q.db.QueryRow(ctx, updateProjectLabel, arg.ID, arg.Name, arg.Color)
	var i ProjectLabel
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
	)
	return i, err
}

const updateProjectMemberRole = `-- name: UpdateProjectMemberRole :exec
UPDATE project_members
SET role = $3
WHERE project_id = $1 AND user_id = $2
`

type UpdateProjectMemberRoleParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateProjectMemberRole, arg.ProjectID, arg.UserID, arg.Role)
	return err
}

const updateProjectState = `-- name: UpdateProjectState :one
UPDATE project_states
SET name = COALESCE($2, name),
    color = COALESCE($3, color),
    position = COALESCE($4, position)
WHERE id = $1
RETURNING id, project_id, state_type, name, color, position, is_default, created_at
`

type UpdateProjectStateParams struct {
	ID       uuid.UUID   `json:"id"`
	Name     pgtype.Text `json:"name"`
	Color    pgtype.Text `json:"color"`
	Position pgtype.Int4 `json:"position"`
}

func (q *Queries) UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (ProjectState, error) {
	row := q.db.QueryRow(ctx, updateProjectState,
		arg.ID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	var i ProjectState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StateType,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = COALESCE($2, title),
    description = COALESCE($3, description),
    state_id = COALESCE($4, state_id),
    priority = COALESCE($5, priority),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, task_number, title, description, state_id, priority, created_by, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
	StateID     pgtype.UUID `json:"state_id"`
	Priority    pgtype.Int4 `json:"priority"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.StateID,
		arg.Priority,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskNumber,
		&i.Title,
		&i.Description,
		&i.StateID,
		&i.Priority,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaskTemplate = `-- name: UpdateTaskTemplate :one
UPDATE task_templates
SET name = COALESCE($2, name),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    updated_at = NOW()
WHERE id = $1
RETURNING id, project_id, name, title, description, created_by, created_at, updated_at
`

type UpdateTaskTemplateParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        pgtype.Text `json:"name"`
	Title       pgtype.Text `json:"title"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) (TaskTemplate, error) {
	row := q.db.QueryRow(ctx, updateTaskTemplate,
		arg.ID,
		arg.Name,
		arg.Title,
		arg.Description,
	)
	var i TaskTemplate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const verifyActivityChain = `-- name: VerifyActivityChain :many
SELECT id, task_id, activity_type, actor_id, field_name, old_value, new_value, created_at, checksum
FROM activity_log
WHERE task_id = $1
ORDER BY created_at ASC
`

func (q *Queries) VerifyActivityChain(ctx context.Context, taskID uuid.UUID) ([]ActivityLog, error) {
	rows, err := q.db.Query(ctx, verifyActivityChain, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityLog{}
	for rows.Next() {
		var i ActivityLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActivityType,
			&i.ActorID,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.Checksum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
