// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UserExistsByEmailOrUsername(ctx context.Context, arg UserExistsByEmailOrUsernameParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
