// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ==================== PROJECT MEMBERS ====================
	AddProjectMember(ctx context.Context, arg AddProjectMemberParams) (ProjectMember, error)
	// ==================== TASK ASSIGNEES ====================
	AddTaskAssignee(ctx context.Context, arg AddTaskAssigneeParams) (TaskAssignee, error)
	// ==================== TASK LABELS ====================
	AddTaskLabel(ctx context.Context, arg AddTaskLabelParams) error
	CountActiveRefreshTokens(ctx context.Context) (int64, error)
	CountAllProjects(ctx context.Context) (int64, error)
	CountAllProjectsFiltered(ctx context.Context, search pgtype.Text) (int64, error)
	CountProjectMembers(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountProjectTasks(ctx context.Context, projectID uuid.UUID) (int64, error)
	CountSearchUsers(ctx context.Context, dollar_1 pgtype.Text) (int64, error)
	CountTaskComments(ctx context.Context, taskID uuid.UUID) (int64, error)
	CountTasksByAssignee(ctx context.Context, userID uuid.UUID) (int64, error)
	CountTasksInState(ctx context.Context, stateID uuid.UUID) (int64, error)
	CountUserActivity(ctx context.Context, actorID uuid.UUID) (int64, error)
	CountUserNotifications(ctx context.Context, actorID uuid.UUID) (int64, error)
	CountUserProjects(ctx context.Context, userID uuid.UUID) (int64, error)
	CountUserProjectsFiltered(ctx context.Context, arg CountUserProjectsFilteredParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// ==================== ACTIVITY LOG ====================
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	// ==================== COMMENTS ====================
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreatePersonalAccessToken(ctx context.Context, arg CreatePersonalAccessTokenParams) (PersonalAccessToken, error)
	// ==================== PROJECTS ====================
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	// ==================== PROJECT LABELS ====================
	CreateProjectLabel(ctx context.Context, arg CreateProjectLabelParams) (ProjectLabel, error)
	// ==================== PROJECT STATES ====================
	CreateProjectState(ctx context.Context, arg CreateProjectStateParams) (ProjectState, error)
	// ==================== PROJECT VIEWS ====================
	CreateProjectView(ctx context.Context, arg CreateProjectViewParams) (ProjectView, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSSOUser(ctx context.Context, arg CreateSSOUserParams) (CreateSSOUserRow, error)
	// ==================== TASKS ====================
	CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error)
	// ==================== TASK TEMPLATES ====================
	CreateTaskTemplate(ctx context.Context, arg CreateTaskTemplateParams) (TaskTemplate, error)
	CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteAttachmentsByEntity(ctx context.Context, arg DeleteAttachmentsByEntityParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeletePersonalAccessToken(ctx context.Context, arg DeletePersonalAccessTokenParams) error
	DeleteProjectLabel(ctx context.Context, id uuid.UUID) error
	DeleteProjectState(ctx context.Context, id uuid.UUID) error
	DeleteTaskTemplate(ctx context.Context, id uuid.UUID) error
	DeleteUpload(ctx context.Context, id uuid.UUID) error
	DeleteUserByID(ctx context.Context, id uuid.UUID) error
	GetCommentByID(ctx context.Context, id uuid.UUID) (GetCommentByIDRow, error)
	GetDefaultProjectState(ctx context.Context, projectID uuid.UUID) (ProjectState, error)
	GetLastActivityChecksum(ctx context.Context, taskID uuid.UUID) (string, error)
	GetNextTaskNumber(ctx context.Context, projectID uuid.UUID) (int32, error)
	GetPersonalAccessTokenByHash(ctx context.Context, tokenHash string) (GetPersonalAccessTokenByHashRow, error)
	GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error)
	GetProjectByKey(ctx context.Context, projectKey string) (Project, error)
	GetProjectLabelByID(ctx context.Context, id uuid.UUID) (ProjectLabel, error)
	GetProjectLabelByProjectAndName(ctx context.Context, arg GetProjectLabelByProjectAndNameParams) (ProjectLabel, error)
	GetProjectMember(ctx context.Context, arg GetProjectMemberParams) (GetProjectMemberRow, error)
	GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error)
	GetProjectStateByID(ctx context.Context, id uuid.UUID) (ProjectState, error)
	// ==================== IMPORT HELPERS ====================
	GetProjectStateByProjectAndName(ctx context.Context, arg GetProjectStateByProjectAndNameParams) (ProjectState, error)
	GetProjectViewByID(ctx context.Context, id uuid.UUID) (ProjectView, error)
	GetProjectViewBySlug(ctx context.Context, arg GetProjectViewBySlugParams) (ProjectView, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (GetTaskByIDRow, error)
	GetTaskByProjectAndNumber(ctx context.Context, arg GetTaskByProjectAndNumberParams) (GetTaskByProjectAndNumberRow, error)
	GetTaskTemplateByID(ctx context.Context, id uuid.UUID) (TaskTemplate, error)
	GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (GetUserByEmailOrUsernameRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (GetUserByProviderIDRow, error)
	HasTaskLabel(ctx context.Context, arg HasTaskLabelParams) (bool, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error)
	LinkProviderToUser(ctx context.Context, arg LinkProviderToUserParams) error
	ListActiveRefreshTokens(ctx context.Context, arg ListActiveRefreshTokensParams) ([]ListActiveRefreshTokensRow, error)
	ListAllProjects(ctx context.Context, arg ListAllProjectsParams) ([]ListAllProjectsRow, error)
	ListAllProjectsFiltered(ctx context.Context, arg ListAllProjectsFilteredParams) ([]ListAllProjectsFilteredRow, error)
	// Filtered list and count are now built dynamically by internal/store/tasks_filter.go
	// from a FilterTree. The projection here is documented for reference by that runner.
	ListAssigneesForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListAssigneesForTasksRow, error)
	ListAttachmentsByEntity(ctx context.Context, arg ListAttachmentsByEntityParams) ([]ListAttachmentsByEntityRow, error)
	ListLabelsForTasks(ctx context.Context, taskIds []uuid.UUID) ([]ListLabelsForTasksRow, error)
	ListPersonalAccessTokensByUser(ctx context.Context, userID uuid.UUID) ([]ListPersonalAccessTokensByUserRow, error)
	ListProjectLabels(ctx context.Context, projectID uuid.UUID) ([]ProjectLabel, error)
	ListProjectMembers(ctx context.Context, projectID uuid.UUID) ([]ListProjectMembersRow, error)
	ListProjectStates(ctx context.Context, projectID uuid.UUID) ([]ProjectState, error)
	ListProjectTasks(ctx context.Context, arg ListProjectTasksParams) ([]ListProjectTasksRow, error)
	// Returns every shared view in the project plus private views owned by the caller.
	ListProjectViews(ctx context.Context, arg ListProjectViewsParams) ([]ProjectView, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	ListTaskActivity(ctx context.Context, taskID uuid.UUID) ([]ListTaskActivityRow, error)
	ListTaskAssignees(ctx context.Context, taskID uuid.UUID) ([]ListTaskAssigneesRow, error)
	ListTaskComments(ctx context.Context, taskID uuid.UUID) ([]ListTaskCommentsRow, error)
	ListTaskLabels(ctx context.Context, taskID uuid.UUID) ([]ListTaskLabelsRow, error)
	ListTaskTemplates(ctx context.Context, projectID uuid.UUID) ([]TaskTemplate, error)
	ListTasksByAssignee(ctx context.Context, arg ListTasksByAssigneeParams) ([]ListTasksByAssigneeRow, error)
	ListUploadsByUser(ctx context.Context, arg ListUploadsByUserParams) ([]Upload, error)
	// ==================== USER ACTIVITY ====================
	ListUserActivity(ctx context.Context, arg ListUserActivityParams) ([]ListUserActivityRow, error)
	ListUserActivityDates(ctx context.Context, arg ListUserActivityDatesParams) ([]ListUserActivityDatesRow, error)
	// ==================== USER NOTIFICATIONS ====================
	// Returns activity on all tasks the user is involved with (creator, assignee, or commenter),
	// excluding the user's own actions. Includes synthetic entries for imported comments without activity_log rows.
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error)
	ListUserProjects(ctx context.Context, arg ListUserProjectsParams) ([]ListUserProjectsRow, error)
	ListUserProjectsFiltered(ctx context.Context, arg ListUserProjectsFilteredParams) ([]ListUserProjectsFilteredRow, error)
	ListUsersPaginated(ctx context.Context, arg ListUsersPaginatedParams) ([]ListUsersPaginatedRow, error)
	ProjectKeyExists(ctx context.Context, projectKey string) (bool, error)
	ProjectViewSlugExists(ctx context.Context, arg ProjectViewSlugExistsParams) (bool, error)
	RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error
	RemoveTaskAssignee(ctx context.Context, arg RemoveTaskAssigneeParams) error
	RemoveTaskLabel(ctx context.Context, arg RemoveTaskLabelParams) error
	// Pass a JSON array of {id, new_position} objects.
	ReorderProjectViews(ctx context.Context, arg ReorderProjectViewsParams) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	SearchUsersPaginated(ctx context.Context, arg SearchUsersPaginatedParams) ([]SearchUsersPaginatedRow, error)
	SoftDeleteComment(ctx context.Context, id uuid.UUID) error
	// When a member leaves a project, their private views are soft-deleted.
	SoftDeleteOwnedPrivateViews(ctx context.Context, arg SoftDeleteOwnedPrivateViewsParams) error
	SoftDeleteProject(ctx context.Context, id uuid.UUID) error
	SoftDeleteProjectView(ctx context.Context, id uuid.UUID) error
	SoftDeleteTask(ctx context.Context, id uuid.UUID) error
	// When a member leaves a project, keep their shared views alive by reassigning ownership.
	TransferOwnedSharedViews(ctx context.Context, arg TransferOwnedSharedViewsParams) error
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdatePersonalAccessTokenLastUsed(ctx context.Context, id uuid.UUID) error
	UpdatePersonalAccessTokenScope(ctx context.Context, arg UpdatePersonalAccessTokenScopeParams) (UpdatePersonalAccessTokenScopeRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectLabel(ctx context.Context, arg UpdateProjectLabelParams) (ProjectLabel, error)
	UpdateProjectMemberRole(ctx context.Context, arg UpdateProjectMemberRoleParams) error
	UpdateProjectState(ctx context.Context, arg UpdateProjectStateParams) (ProjectState, error)
	UpdateProjectView(ctx context.Context, arg UpdateProjectViewParams) (ProjectView, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error)
	UpdateTaskTemplate(ctx context.Context, arg UpdateTaskTemplateParams) (TaskTemplate, error)
	UpdateUserAvatarURL(ctx context.Context, arg UpdateUserAvatarURLParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserType(ctx context.Context, arg UpdateUserTypeParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) (Setting, error)
	UserExistsByEmailOrUsername(ctx context.Context, arg UserExistsByEmailOrUsernameParams) (bool, error)
	VerifyActivityChain(ctx context.Context, taskID uuid.UUID) ([]ActivityLog, error)
}

var _ Querier = (*Queries)(nil)
