// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: uploads.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createUpload = `-- name: CreateUpload :one
INSERT INTO uploads (filename, stored_name, mime_type, size_bytes, uploaded_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, filename, stored_name, mime_type, size_bytes, uploaded_by, created_at
`

type CreateUploadParams struct {
	Filename   string    `json:"filename"`
	StoredName string    `json:"stored_name"`
	MimeType   string    `json:"mime_type"`
	SizeBytes  int64     `json:"size_bytes"`
	UploadedBy uuid.UUID `json:"uploaded_by"`
}

func (q *Queries) CreateUpload(ctx context.Context, arg CreateUploadParams) (Upload, error) {
	row := q.db.QueryRow(ctx, createUpload,
		arg.Filename,
		arg.StoredName,
		arg.MimeType,
		arg.SizeBytes,
		arg.UploadedBy,
	)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUpload = `-- name: DeleteUpload :exec
DELETE FROM uploads WHERE id = $1
`

func (q *Queries) DeleteUpload(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUpload, id)
	return err
}

const getUploadByID = `-- name: GetUploadByID :one
SELECT id, filename, stored_name, mime_type, size_bytes, uploaded_by, created_at
FROM uploads
WHERE id = $1
`

func (q *Queries) GetUploadByID(ctx context.Context, id uuid.UUID) (Upload, error) {
	row := q.db.QueryRow(ctx, getUploadByID, id)
	var i Upload
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.StoredName,
		&i.MimeType,
		&i.SizeBytes,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listUploadsByUser = `-- name: ListUploadsByUser :many
SELECT id, filename, stored_name, mime_type, size_bytes, uploaded_by, created_at
FROM uploads
WHERE uploaded_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUploadsByUserParams struct {
	UploadedBy uuid.UUID `json:"uploaded_by"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListUploadsByUser(ctx context.Context, arg ListUploadsByUserParams) ([]Upload, error) {
	rows, err := q.db.Query(ctx, listUploadsByUser, arg.UploadedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Upload{}
	for rows.Next() {
		var i Upload
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.StoredName,
			&i.MimeType,
			&i.SizeBytes,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
